// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Domain.Models.Dataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("id");

                    b.Property<byte[]>("ImageMatrix")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB")
                        .HasColumnName("image");

                    b.Property<bool>("IsTest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("is_test");

                    b.Property<int>("Label")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("label");

                    b.HasKey("Id")
                        .HasName("pk_datasetid");

                    b.ToTable("Dataset");
                });
#pragma warning restore 612, 618
        }
    }
}
